/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programacion;


/** Formulario principal
 *
 * @author Víctor Díaz
 */
public class FrmInicial extends javax.swing.JFrame {

    
    // Constante usada para títulos de JOptionPane
    public static final String ATENCION = "ATENCION!!!";
    
    /**
     * Creates new form Main
     */
    public FrmInicial() {
        initComponents();        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInicial().setVisible(true);
            }
        });
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLog = new javax.swing.JButton();
        btnRexistro = new javax.swing.JButton();
        btnFin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setSize(new java.awt.Dimension(400, 350));

        btnLog.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnLog.setText("Loguearse");
        btnLog.setActionCommand("btnLog");
        btnLog.setName("btnLog"); // NOI18N
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLog_click(evt);
            }
        });

        btnRexistro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnRexistro.setActionCommand("btnRexistro");
        btnRexistro.setLabel("Rexistrarse");
        btnRexistro.setName("btnRexistro"); // NOI18N
        btnRexistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRexistro_click(evt);
            }
        });

        btnFin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnFin.setText("Fin");
        btnFin.setActionCommand("btnFin");
        btnFin.setName("btnFin"); // NOI18N
        btnFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFin(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Tarefa AD06: miniTwitter");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFin)
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRexistro, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(btnRexistro, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnFin)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRexistro_click(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRexistro_click
        // Creamos o formulario de rexistro e o amosamos
        FrmRexistro rexistro = new FrmRexistro(this, true);
        rexistro.setVisible(true);
        
    }//GEN-LAST:event_btnRexistro_click

    private void btnLog_click(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLog_click
        // Creamos o formulario de logueo e o amosamos
        FrmLog logueo = new FrmLog(this, true);
        logueo.setVisible(true);
    }//GEN-LAST:event_btnLog_click

    private void btnFin(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFin
        // Remtar aplicación
        System.exit(0);
    }//GEN-LAST:event_btnFin
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFin;
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnRexistro;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
