/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programacion;

import Clases.BaseDatos;
import Clases.Usuario;


/** Formulario que contén o menú principal
 *
 * @author Víctor Díaz
 */
public class FrmMenu extends javax.swing.JDialog {

    protected static Usuario usuario;
    
    /**
     * Creates new form FrmMenu
     */
    public FrmMenu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        usuario = FrmLog.db.getUsuario(FrmLog.nickUsuario);
    }

    private void verMensaxes(String opcion) {
        
        // Amosamos o formulario de ver mensaxes, pasándolle se son Todas, de Usuarios ou Hashtag
        FrmVerMensaxes verMensaxes = new FrmVerMensaxes(new javax.swing.JFrame(), true, opcion);
        verMensaxes.setVisible(true);}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnVerMensaxes = new javax.swing.JButton();
        btnVerMensaxesUsuarios = new javax.swing.JButton();
        btnVerMensaxesHashtag = new javax.swing.JButton();
        btnEscribirMensaxe = new javax.swing.JButton();
        btnBuscarUsuarios = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menú principal");

        btnVerMensaxes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnVerMensaxes.setText("Ver TODAS as mensaxes");
        btnVerMensaxes.setActionCommand("btnVerMensaxes");
        btnVerMensaxes.setName("btnVerMensaxes"); // NOI18N
        btnVerMensaxes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerMensaxes_click(evt);
            }
        });

        btnVerMensaxesUsuarios.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnVerMensaxesUsuarios.setText("Ver mensaxes de USUARIOS que sigo");
        btnVerMensaxesUsuarios.setActionCommand("btnVerMensaxesUsuario");
        btnVerMensaxesUsuarios.setName("btnVerMensaxesUsuarios"); // NOI18N
        btnVerMensaxesUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerMensaxesUsuarios_click(evt);
            }
        });

        btnVerMensaxesHashtag.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnVerMensaxesHashtag.setText("Buscar mensaxes por HASHTAG");
        btnVerMensaxesHashtag.setActionCommand("btnVerMensaxesHashtag");
        btnVerMensaxesHashtag.setName("btnVerMensaxesHashtag"); // NOI18N
        btnVerMensaxesHashtag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerMensaxesHashtag_click(evt);
            }
        });

        btnEscribirMensaxe.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEscribirMensaxe.setText("ESCRIBIR Mensaxe");
        btnEscribirMensaxe.setToolTipText("");
        btnEscribirMensaxe.setActionCommand("btnEscribirMensaxe");
        btnEscribirMensaxe.setName("btnEscribirMensaxe"); // NOI18N
        btnEscribirMensaxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscribirMensaxe_click(evt);
            }
        });

        btnBuscarUsuarios.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnBuscarUsuarios.setText("Busar USUARIOS");
        btnBuscarUsuarios.setToolTipText("");
        btnBuscarUsuarios.setActionCommand("btnBuscarUsuarios");
        btnBuscarUsuarios.setName("btnBuscarUsuarios"); // NOI18N
        btnBuscarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUsuarios_click(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setName("btnCancelar"); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar_click(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEscribirMensaxe, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerMensaxesHashtag, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerMensaxesUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerMensaxes, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(btnVerMensaxes, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVerMensaxesUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVerMensaxesHashtag, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btnEscribirMensaxe, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnBuscarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(28, 28, 28))
        );

        btnEscribirMensaxe.getAccessibleContext().setAccessibleName("Escribir Mensaxe");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerMensaxes_click(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerMensaxes_click
        
        // Ver todas as mensaxes
        verMensaxes("T");
        

    }//GEN-LAST:event_btnVerMensaxes_click

    private void btnVerMensaxesUsuarios_click(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerMensaxesUsuarios_click
        // actualizamos información do usuario por se modificou a quen segue
        usuario = FrmLog.db.getUsuario(FrmLog.nickUsuario);
        
        // ver mensaxes de usuarios que sigo
        verMensaxes("U");
    }//GEN-LAST:event_btnVerMensaxesUsuarios_click

    private void btnVerMensaxesHashtag_click(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerMensaxesHashtag_click
        // ver mensaxes por hashtag
        verMensaxes("H");
    }//GEN-LAST:event_btnVerMensaxesHashtag_click

    private void btnEscribirMensaxe_click(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscribirMensaxe_click
                        
        // Amosamos o formulario para escribir mensaxes
        FrmEscribirMensaxe escribirMensaxe = new FrmEscribirMensaxe(new javax.swing.JFrame(), true);
        escribirMensaxe.setVisible(true);
    }//GEN-LAST:event_btnEscribirMensaxe_click

    private void btnBuscarUsuarios_click(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUsuarios_click
        
// Amosamos o formulario para buscar usuarios
        FrmBuscarUsuarios buscarUsuarios = new FrmBuscarUsuarios(new javax.swing.JFrame(), true);
        buscarUsuarios.setVisible(true);
    }//GEN-LAST:event_btnBuscarUsuarios_click

    private void btnCancelar_click(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar_click
        this.dispose();
    }//GEN-LAST:event_btnCancelar_click

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmMenu dialog = new FrmMenu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarUsuarios;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEscribirMensaxe;
    private javax.swing.JButton btnVerMensaxes;
    private javax.swing.JButton btnVerMensaxesHashtag;
    private javax.swing.JButton btnVerMensaxesUsuarios;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
